apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-sejutacita-deployment
spec:
  selector:
    matchLabels:
      app: api-sejutacita
  replicas: 1
  template:
    metadata:
      labels:
        app: api-sejutacita
        env: development
    spec:
      containers:
      - name: api-sejutacita
        image: gcr.io/fast-audio-337101/app:v1
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: api-sejutacita-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: api-sejutacita